name: retina
description: Real-Time Indoor Navigation Assistant 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^1.10.5
  provider: ^4.0.4
  http: ^0.12.0+4
  dio: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
          - asset: fonts/Montserrat/Montserrat-Bold.ttf
          - asset: fonts/Montserrat/Montserrat-Italic.ttf
            style: italic
          - asset: fonts/Montserrat/Montserrat-Light.ttf
          - asset: fonts/Montserrat/Montserrat-Medium.ttf
          - asset: fonts/Montserrat/Montserrat-Regular.ttf
          - asset: fonts/Montserrat/Montserrat-Thin.ttf
  